version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=achatdb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-achat:
    depends_on:
      - mysqldb
    image: abidimaryem14/achat:1.0.0
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": null,
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true
  frontend:
    image: docker.pkg.github.com/meriamabidi/devopsprojet/frontend:latest
    restart: unless-stopped
    ports:
      - 4401:4401
    depends_on:
      - app-achat
volumes:
  db:
